services:
  - type: web
    name: emkost-rf
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.22.0
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_TARGET_CHAT
        sync: false
